### ISSUE TITLE
I want to use VLLM to speed up inference llm.pt model in Cosyvoice 

### ISSUE THREAD

**Issue by Horizon-Chaser** [tongxiao2002/vllm-for-LMMS#1]
I want to use VLLM to speed up inference llm.pt model in Cosyvoice Can I add your WeChat to ask you?Thank you

**Comment by tongxiao2002** [comment]
Sure, you could send me your WeChat ID or phone number to my email: [tongxiao2002@mail.ustc.edu.cn](mailto:tongxiao2002@mail.ustc.edu.cn), then we can discuss in detail.

**Comment by Horizon-Chaser** [comment]
ok,Sent

**Comment by nantatian** [comment]
> 我想用 VLLM 加速推理 llm.pt Cosyvoice 模型可以加你的微信问你吗？谢谢

您好，我想问一下，您这边可以实现vllm加速推理吗
